.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SANDBOX" "1" "November 2010" "DevStructure" "Sandbox"
.
.SH "NAME"
\fBsandbox\fR \- sandbox entire UNIX servers
.
.SH "SYNOPSIS"
\fBsandbox\fR [\fIcommand\fR] [\fIoptions\fR][\fI\.\.\.\fR]
.
.SH "DESCRIPTION"
\fBsandbox\fR programs are used to sandbox entire UNIX servers to avoid polluting the base sandbox (the actual server) when doing experimental or invasive work\. Sandboxes stop short of full virtualization and as such are quick to create, use, and destroy\. Each sandbox contains a deep copy of your home directory and a shallow copy of the rest of the server\'s filesystem\. Packages can be installed as usual, configuration can be changed, and services can be started within each sandbox\. It is, however, possible for network ports to conflict between sandboxes\.
.
.TP
\fBsandbox\-list\fR(1)
List all sandboxes\.
.
.TP
\fBsandbox\-which\fR(1)
Print the name of the current sandbox\.
.
.TP
\fBsandbox\-create\fR(1)
Create a new sandbox\.
.
.TP
\fBsandbox\-clone\fR(1)
Clone an existing sandbox\.
.
.TP
\fBsandbox\-use\fR(1)
Run commands in a sandbox\.
.
.TP
\fBsandbox\-mark\fR(1)
Mark arbitrary files for inclusion in a blueprint\.
.
.TP
\fBsandbox\-destroy\fR(1)
Destroy a sandbox\.
.
.SH "EXAMPLES"
Create a sandbox called \fImq\-worker\fR and install the Ruby gems necessary to work from a message queue\. Then clone that sandbox to another called \fImq\-broker\fR and install the rabbitmq\-server AMQP broker and unlock its configuration file so we can modify it later\.
.
.IP "" 4
.
.nf

sandbox create mq\-worker
sandbox use mq\-worker
sudo gem install amqp carrot
exit
sandbox clone mq\-worker mq\-broker
sandbox use mq\-broker \-c "sudo apt\-get \-y install rabbitmq\-server"
sandbox unlock mq\-broker /etc/rabbitmq/rabbitmq\.conf
.
.fi
.
.IP "" 0
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
\fBsandbox\-list\fR(1), \fBsandbox\-which\fR(1), \fBsandbox\-create\fR(1), \fBsandbox\-clone\fR(1), \fBsandbox\-use\fR(1), and \fBsandbox\-destroy\fR(1)\.
