.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SANDBOXFS" "1" "November 2010" "DevStructure" "Sandbox"
.
.SH "NAME"
\fBsandboxfs\fR \- copy\-on\-write filesystem
.
.SH "SYNOPSIS"
\fBsandboxfs\fR \fB\-oallow_other\fR [\fImountpoint\fR] [\fB\-f\fR]
.
.SH "DESCRIPTION"
\fBsandboxfs\fR implements a copy\-on\-write filesystem designed to reduce users\' need to use \fBblueprint\-mark\fR(1)\. Each sandbox has a "shadow" directory that contains the backing filesystem trees used by \fBsandboxfs\fR, located at /var/sandboxes/\.\fIsandbox\fR\.
.
.P
By default, a \fBsandboxfs\fR will be mounted in each sandbox at /etc\.
.
.SH "OPTIONS"
.
.TP
\fB\-oallow_other\fR
Allow users other than the mounting user to access files on this device\. In general, the mounting user is root so this option must be supplied for normal users to go about their business\.
.
.TP
\fImountpoint\fR
The directory to which the filesystem is attached\. Generally, this takes the form /var/sandboxes/\fIsandbox\fR/etc\.
.
.TP
\fB\-f\fR
Do not retreat into the background\. This will produce copious output and is mainly available for debugging purposes\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBsandbox\fR(1)\.
.
.P
\fBsandbox\-list\fR(1), \fBsandbox\-which\fR(1), \fBsandbox\-create\fR(1), \fBsandbox\-clone\fR(1), \fBsandbox\-use\fR(1), and \fBsandbox\-destroy\fR(1)\.
