.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SANDBOX\-USE" "1" "November 2010" "DevStructure" "Sandbox"
.
.SH "NAME"
\fBsandbox\-use\fR \- run commands in a sandbox
.
.SH "SYNOPSIS"
\fBsandbox use\fR \fIsandbox\fR [\fB\-c\fR \fIcommand\fR] [\fB\-\-callback=\fR\fIcallback\fR] [\fB\-q\fR] [\fB\-h\fR]
.
.SH "DESCRIPTION"
\fBsandbox\-use\fR runs commands in a sandbox\. If no command is specified, your login shell is run and is given the \fB\-i\fR and \fB\-l\fR arguments\. The \fIcommand\fR will be run as you\.
.
.P
Regardless of what command is run, the \fIcallback\fR command, if given, will follow the termination of \fIcommand\fR\.
.
.SH "OPTIONS"
.
.TP
\fIsandbox\fR
Name of a sandbox\.
.
.TP
\fB\-c\fR \fIcommand\fR, \fB\-\-command=\fR\fIcommand\fR
Command to run\. Defaults to your shell\.
.
.TP
\fB\-\-callback=\fR\fIcallback\fR
Command to run when \fIcommand\fR exits\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBsandbox\fR(1)\.
.
.P
\fBsandbox\-list\fR(1), \fBsandbox\-which\fR(1), \fBsandbox\-create\fR(1), \fBsandbox\-clone\fR(1), \fBsandbox\-use\fR(1), and \fBsandbox\-destroy\fR(1)\.
